name: commitlint_cli
description:
  Commitlint is a tool for lint commit messages.
  This package is the commitlint command line tool entry.
version: 0.2.1
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_cli
documentation: https://hyiso.github.io/commitlint

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  commitlint_format: ^0.1.1
  commitlint_lint: ^0.2.0
  commitlint_load: ^0.1.1
  commitlint_read: ^0.2.1
  commitlint_types: ^0.2.0
  path: ^1.8.0
  meta: ^1.8.0
  yaml: ^3.1.1
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
