name: commitlint_config
description:
  Commitlint is a tool for lint commit messages.
  This package is for common and recommend configurations.
version: 0.1.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_config

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
