name: commitlint_read
description:
  Commitlint is a tool for lint commit messages.
  This package is for reading commit messages according to arguments passed.
version: 0.2.1
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_read
documentation: https://hyiso.github.io/commitlint

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  uuid: ^3.0.7
