name: commitlint_read
description: A package used for commlint cli to read commit messages in given range(from, to), or in given file (default ./.git/COMMIT_EDITMSG).
version: 0.1.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_read

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
