name: commitlint_lint
description:
  Commitlint is a tool for lint commit messages.
  This package is for linting commit messages according to configured rules.
version: 0.2.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_lint
documentation: https://hyiso.github.io/commitlint

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  commitlint_parse: ^0.1.0
  commitlint_rules: ^0.2.0
  commitlint_types: ^0.2.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
