name: commitlint_lint
description:
  Commitlint is a tool for lint commit messages.
  This package is for linting commit messages according to configured rules.
version: 0.1.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_lint
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  commitlint_rules: ^0.1.0
  commitlint_types: ^0.1.0
  conventional_commit: ^0.5.0+1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
