name: commitlint_load
description:
  Commitlint is a tool for lint commit messages.
  This package is for loading commitlint config rules.
version: 0.1.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_load

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  commitlint_types: ^0.1.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
