name: commitlint_rules
description:
  Commitlint is a tool for lint commit messages.
  This is the rules package for commitlint cli package.
version: 0.1.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_rules

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  change_case: ^1.0.0+3
  conventional_commit: ^0.5.0+1
  commitlint_types: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
