name: commitlint_rules
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  change_case: ^1.0.0+3
  conventional_commit: ^0.5.0+1
  commitlint_types: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
