name: commitlint_format
description:
  Commitlint is a tool for lint commit messages.
  This package is for formatting the result of lint package.
version: 0.1.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  colorize: ^3.0.0
  commitlint_types: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
