name: commitlint_cli
description: A lint to for commit message.
version: 0.0.1
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/cli

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  commitlint:
