name: commitlint_types
description:
  Commitlint is a tool for lint commit messages.
  This is the types package for commitlint cli package.
version: 0.1.0
homepage: https://github.com/hyiso/commitlint
repository: https://github.com/hyiso/commitlint/packages/commitlint_types

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  conventional_commit: ^0.5.0+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
